model: gpt-4o-mini
temperature: 0.7
max_tokens: 512
agent_counts: [1, 5, 10, 15, 20, 25]
context_lengths: [50, 100, 200, 400, 800]
stories_per_length: 10
metric: rouge_l
source_text_path: source_text.txt 